import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Remote photography is served straight from the Unsplash CDN with
    // responsive widths generated by our custom loader.
    loader: "custom",
    loaderFile: "./lib/image-loader.ts",
  },
};

export default nextConfig;
